language: go
sudo: required

go:
  - 1.8
  - 1.9

env:
  - GERRITTEST_DOCKER_IMAGE=opalmer/gerrittest:2.14.2
  - GERRITTEST_DOCKER_IMAGE=opalmer/gerrittest:2.14.3
  - GERRITTEST_DOCKER_IMAGE=opalmer/gerrittest:2.14.4

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash)
