language: go
sudo: required

go:
    - 1.8
    - 1.9

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash)
